services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: astra
      POSTGRES_PASSWORD: astra@123
      POSTGRES_DB: astra_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=astra_db
      - DJANGO_DB_USER=astra
      - DJANGO_DB_PASSWORD=astra@123

volumes:
  postgres_data:
