# Generated by Django 5.1.5 on 2025-01-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_management.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business_management.items')),
                ('action', models.CharField(default=None, max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('shipment_date', models.DateField(default=None)),
                ('location', models.CharField(choices=[('Hokkaido', '北海道'), ('Aomori', '青森'), ('Iwate', '岩手'), ('Miyagi', '宮城'), ('Akita', '秋田'), ('Yamagata', '山形'), ('Fukushima', '福島'), ('Ibaraki', '茨城'), ('Tochigi', '栃木'), ('Gunma', '群馬'), ('Saitama', '埼玉'), ('Chiba', '千葉'), ('Tokyo', '東京'), ('Kanagawa', '神奈川'), ('Niigata', '新潟'), ('Toyama', '富山'), ('Ishikawa', '石川'), ('Fukui', '福井'), ('Yamanashi', '山梨'), ('Nagano', '長野'), ('Gifu', '岐阜'), ('Shizuoka', '静岡'), ('Aichi', '愛知'), ('Mie', '三重'), ('Shiga', '滋賀'), ('Kyoto', '京都'), ('Osaka', '大阪'), ('Hyogo', '兵庫'), ('Nara', '奈良'), ('Wakayama', '和歌山'), ('Tottori', '鳥取'), ('Shimane', '島根'), ('Okayama', '岡山'), ('Hiroshima', '広島'), ('Yamaguchi', '山口'), ('Tokushima', '徳島'), ('Kagawa', '香川'), ('Ehime', '愛媛'), ('Kochi', '高知'), ('Fukuoka', '福岡'), ('Saga', '佐賀'), ('Nagasaki', '長崎'), ('Kumamoto', '熊本'), ('Oita', '大分'), ('Miyazaki', '宮崎'), ('Kagoshima', '鹿児島'), ('Okinawa', '沖縄')], max_length=100)),
            ],
            options={
                'db_table': 'shipment_log',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business_management.items')),
                ('location', models.CharField(choices=[('Hokkaido', '北海道'), ('Aomori', '青森'), ('Iwate', '岩手'), ('Miyagi', '宮城'), ('Akita', '秋田'), ('Yamagata', '山形'), ('Fukushima', '福島'), ('Ibaraki', '茨城'), ('Tochigi', '栃木'), ('Gunma', '群馬'), ('Saitama', '埼玉'), ('Chiba', '千葉'), ('Tokyo', '東京'), ('Kanagawa', '神奈川'), ('Niigata', '新潟'), ('Toyama', '富山'), ('Ishikawa', '石川'), ('Fukui', '福井'), ('Yamanashi', '山梨'), ('Nagano', '長野'), ('Gifu', '岐阜'), ('Shizuoka', '静岡'), ('Aichi', '愛知'), ('Mie', '三重'), ('Shiga', '滋賀'), ('Kyoto', '京都'), ('Osaka', '大阪'), ('Hyogo', '兵庫'), ('Nara', '奈良'), ('Wakayama', '和歌山'), ('Tottori', '鳥取'), ('Shimane', '島根'), ('Okayama', '岡山'), ('Hiroshima', '広島'), ('Yamaguchi', '山口'), ('Tokushima', '徳島'), ('Kagawa', '香川'), ('Ehime', '愛媛'), ('Kochi', '高知'), ('Fukuoka', '福岡'), ('Saga', '佐賀'), ('Nagasaki', '長崎'), ('Kumamoto', '熊本'), ('Oita', '大分'), ('Miyazaki', '宮崎'), ('Kagoshima', '鹿児島'), ('Okinawa', '沖縄')], max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.items')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_quantity', models.IntegerField()),
                ('due_date', models.DateField()),
                ('estimated_completion_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.order')),
            ],
            options={
                'db_table': 'production',
            },
        ),
    ]
