# Generated by Django 5.1.4 on 2024-12-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
