# Generated by Django 5.1.5 on 2025-01-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0002_order_delivery_date_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
